POST http://localhost:3001/api/auth/login
Content-Type: application/json


{
    "name":"Eduardo",
    "email":"eduz211004@gmail.com",
    "password":"Daniel211004",
    "bio":"Never expect something better, better things always brings sadder moods"
}